# Site settings
title: Page Transition Test
email: swashcap@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  _Page Transition Test_ is an experimental blog layout and page-to-page
  transition site. It utilizes [Jekyll](http://jekyllrb.com/) to generate
  the HTML, and custom CSS animations and JavaScript power the animations
  (loosely based on [Codrops’ Page Transitions](http://tympanus.net/codrops/2013/05/07/a-collection-of-page-transitions/)).
baseurl: "/page-transition" # the subpath of your site, e.g. /blog/
url: "http://swashcap.github.io" # the base hostname & protocol for your site

permalink: "/:year/:month/:title/"

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
